name: build and deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      message:
        description: "give some input for the file"
        required: true
        default: "Hello Team"
  

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: executable (run script)
        run: chmod +x scripts/build.sh
            
      - name: run the script
        run: ./scripts/build.sh "${{ inputs.message }}"

      - name: display output
        run: cat output.txt
