name: build and deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      servers:
        description: "comma-seperated servers"
        required: true
        default: "1,2,3"
  

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: executable (run script)
        run: chmod +x scripts/build.sh
            
      - name: run the script
        run: ./scripts/build.sh "${{ inputs.servers }}"

      - name: display output
        run: cat output.txt
